title: Zehao Zhou's Homepage
page-top-title: Zehao Zhou
top-section-bg-text: Computational Chemistry
home-subtitle: Zehao Zhou&ensp;|&ensp;周泽浩
copyright-text: '&copy; Zehao Zhou 2023-2025. All Rights Reserved.'
